### POST request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Jake",
  "email": "jake@gmail.com",
  "dateOfBirth": "1999-09-09",
  "address": "NY",
  "registrationDate": "2025-03-28"
}
###